### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by justinGilmer**

### CODE REVIEW

**Comment by justinGilmer** [comment]
Vanta Remediate Critical vulnerabilities [sc-28165]

**Comment by justinGilmer** [comment]
Vanta Remediate Critical vulnerabilities [sc-28166]

**Comment by justinGilmer** [comment]
Vanta Remediate Critical vulnerabilities [sc-28165]

**Comment by justinGilmer** [comment]
Vanta Remediate Critical vulnerabilities [sc-28167]

**Review by youngale-pingthings — APPROVED** [review]

**Pull request merged**
